from __future__ import annotations

import json
import subprocess
from pathlib import Path
import os
import textwrap
import typer
import httpx
from rich.console import Console

from ..paths import ensure_workdir

app = typer.Typer(no_args_is_help=True)
console = Console()


def download_cover_image(url: str, save_path: Path) -> bool:
    """Download cover image from URL to local path."""
    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.get(url)
            response.raise_for_status()

            # Ensure parent directory exists
            save_path.parent.mkdir(parents=True, exist_ok=True)

            with open(save_path, 'wb') as f:
                f.write(response.content)

        console.print(f"[green]✅ 封面已下载: {save_path}[/green]")
        return True
    except Exception as e:
        console.print(f"[yellow]⚠️  封面下载失败: {e}[/yellow]")
        return False


@app.command("config")
def config(
    video_id: str = typer.Option(..., "--video-id", "-v", help="视频 ID"),
    workdir: Path = typer.Option(Path(os.getenv("YOUDOUB_WORKDIR", "./work")), "--workdir", "-w", help="Workspace directory"),
    title: str = typer.Option("", "--title", help="BiliBili title (default from meta.json if available)"),
    desc: str = typer.Option("", "--desc", help="BiliBili description"),
    tags: str = typer.Option("", "--tags", help="Comma-separated tags"),
    tid: int = typer.Option(0, "--tid", help="BiliBili partition id (tid)"),
    subtitle_mode: str = typer.Option("zh", "--subtitle-mode", help="zh or bilingual"),
    copyright: int = typer.Option(2, "--copyright", help="Copyright: 1-自制 2-转载"),
    source: str = typer.Option("Youtube", "--source", help="转载来源 (当 copyright=2 时使用)"),
    cover: str = typer.Option("", "--cover", help="本地封面文件路径 (留空则使用抓取的链接)"),
):
    """Generate biliup.yaml config in workdir/bili for later upload."""
    # Compute target workspace path
    target_root = workdir / video_id
    wp = ensure_workdir(target_root)

    console.print(f"视频 ID: {video_id}")
    console.print(f"工作目录: {target_root}")

    # choose subtitle output
    subtitle_path = wp.out_zh() if subtitle_mode == "zh" else wp.out_bilingual

    # Try load title from meta
    meta_title = ""
    thumbnail_url = ""
    if wp.meta_json.exists():
        try:
            meta = json.loads(wp.meta_json.read_text(encoding="utf-8"))
            meta_title = meta.get("title") or ""
            desc = meta.get("description") or ""
            thumbnail_url = meta.get("thumbnail") or ""
        except Exception:
            meta_title = ""

    title_final = title or meta_title or "Untitled"

    # Handle cover image
    final_cover = cover  # User provided cover parameter
    if not final_cover and thumbnail_url:
        # No user cover provided, use thumbnail from meta
        if thumbnail_url.startswith('http://') or thumbnail_url.startswith('https://'):
            # It's a URL, download it
            cover_filename = f"{video_id}_cover.jpg"
            cover_path = wp.root / cover_filename
            if download_cover_image(thumbnail_url, cover_path):
                final_cover = str(cover_path)
            # else: download failed, final_cover remains empty
        else:
            # It's already a local path
            final_cover = thumbnail_url

    cover = final_cover

    tag_list = [t.strip() for t in tags.split(",") if t.strip()]

    # biliup config template with correct streamers format
    # NOTE: biliup config schema may differ by version; user can edit this file.
    video_path_str = json.dumps(str(wp.video), ensure_ascii=False)

    # Build configuration using template
    config_data = {
        'title': title_final,
        'desc': desc or "",
        'tid': tid or 0,
        'tags': tag_list or [],
        'cover': cover,
        'copyright': copyright,
        'source': source,
    }

    # Build YAML content
    yaml_lines = [
        "# Auto-generated by youdoub",
        "# biliup configuration file",
        "",
        "streamers:",
        f"  {video_path_str}:",
        f"    title: {json.dumps(config_data['title'], ensure_ascii=False)}",
        f"    desc: {json.dumps(config_data['desc'], ensure_ascii=False)}",
        f"    tid: {config_data['tid']}",
        f"    tags: {json.dumps(config_data['tags'], ensure_ascii=False)}",
    ]

    # Only add cover if it's provided
    if config_data['cover']:
        yaml_lines.append(f"    cover: {json.dumps(config_data['cover'], ensure_ascii=False)}")

    yaml_lines.extend([
        f"    copyright: {config_data['copyright']}",
        f"    source: {json.dumps(config_data['source'], ensure_ascii=False)}",
    ])

    yaml = "\n".join(yaml_lines)

    # Subtitles: biliup support varies; we include a hint section.
    yaml += "\n\n# Subtitle hint (may require manual integration depending on biliup version)"
    yaml += "\n# subtitle:"
    yaml += f"\n#   path: {json.dumps(str(subtitle_path), ensure_ascii=False)}"

    wp.bili_config.write_text(yaml, encoding="utf-8")
    console.print(f"[green]OK[/green] wrote config: {wp.bili_config}")
    console.print("You may need to edit this yaml to match your biliup version/schema.")
    console.print(f"Hint: run `youdoub bili upload` to upload, or `youdoub bili submit` for one-click submission.")


@app.command("upload")
def upload(
    video_id: str = typer.Option(..., "--video-id", "-v", help="视频 ID"),
    workdir: Path = typer.Option(Path(os.getenv("YOUDOUB_WORKDIR", "./work")), "--workdir", "-w", help="Workspace directory"),
    biliup_bin: str = typer.Option("biliup", "--biliup-bin", help="biliup executable"),
):
    """Upload to BiliBili via biliup using workdir/bili/biliup.yaml."""
    # Compute target workspace path
    target_root = workdir / video_id
    wp = ensure_workdir(target_root)

    console.print(f"视频 ID: {video_id}")
    console.print(f"工作目录: {target_root}")

    if not wp.bili_config.exists():
        console.print(f"[red]Error: Missing biliup config {wp.bili_config}[/red]")
        console.print("Hint: run `youdoub bili config ...` first.")
        raise typer.Exit(1)

    # Check if biliup is installed
    try:
        if biliup_bin == "biliup":
            subprocess.run(["uv", "run", "biliup", "--version"], capture_output=True, check=True)
        else:
            subprocess.run([biliup_bin, "--version"], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        console.print(f"[red]❌ biliup 未安装或无法找到[/red]")
        console.print()
        console.print("[blue]安装 biliup 的方法：[/blue]")
        console.print("1. 使用 uv 安装 (推荐):")
        console.print("   [cyan]uv pip install biliup[/cyan]")
        console.print()
        console.print("2. 或者使用 pip 安装:")
        console.print("   [cyan]pip install biliup[/cyan]")
        console.print()
        console.print("3. 验证安装:")
        console.print("   [cyan]uv run biliup --version[/cyan]")
        console.print()
        console.print(f"4. 配置 BiliBili 账号:")
        console.print("   [cyan]uv run biliup login[/cyan]")
        console.print()
        console.print("安装完成后重新运行此命令。")
        raise typer.Exit(1)

    # Call biliup via uv run if biliup_bin is 'biliup' (default)
    if biliup_bin == "biliup":
        cmd = ["uv", "run", "biliup", "upload", "-c", str(wp.bili_config)]
    else:
        cmd = [biliup_bin, "upload", "-c", str(wp.bili_config)]
    console.print("Running: " + " ".join(cmd))

    try:
        cp = subprocess.run(cmd)
    except FileNotFoundError as e:
        if biliup_bin == "biliup":
            console.print(f"[red]❌ 无法找到 biliup 命令: {e}[/red]")
            console.print("请确保 biliup 已通过 uv 安装: uv pip install biliup")
            console.print("然后使用: uv run biliup --version")
        else:
            console.print(f"[red]❌ 无法找到 biliup 命令: {e}[/red]")
            console.print(f"指定的 biliup 可执行文件不存在: {biliup_bin}")
        raise typer.Exit(1)

    result = {
        "command": cmd,
        "returncode": cp.returncode,
    }
    wp.bili_result.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")

    if cp.returncode != 0:
        console.print(f"[red]❌ 上传失败[/red], 返回码={cp.returncode}")
        console.print(f"详细结果请查看: {wp.bili_result}")
        console.print()
        console.print("[blue]常见解决方案：[/blue]")
        console.print("1. 检查 BiliBili 账号是否已登录: [cyan]biliup login[/cyan]")
        console.print("2. 检查视频文件是否存在且不损坏")
        console.print("3. 检查网络连接")
        console.print("4. 查看详细错误日志")
        raise typer.Exit(cp.returncode)

    console.print(f"[green]OK[/green] upload finished. Result: {wp.bili_result}")


@app.command("submit")
def submit(
    video_id: str = typer.Option(..., "--video-id", "-v", help="视频 ID"),
    workdir: Path = typer.Option(Path(os.getenv("YOUDOUB_WORKDIR", "./work")), "--workdir", "-w", help="Workspace directory"),
    title: str = typer.Option("", "--title", help="BiliBili title (default from meta.json if available)"),
    desc: str = typer.Option("", "--desc", help="BiliBili description"),
    tags: str = typer.Option("", "--tags", help="Comma-separated tags"),
    tid: int = typer.Option(0, "--tid", help="BiliBili partition id (tid)"),
    subtitle_mode: str = typer.Option("zh", "--subtitle-mode", help="zh or bilingual"),
    biliup_bin: str = typer.Option("biliup", "--biliup-bin", help="biliup executable"),
    force_config: bool = typer.Option(False, "--force-config", help="Regenerate config even if it exists"),
    copyright: int = typer.Option(1, "--copyright", help="Copyright: 1-自制 2-转载"),
    source: str = typer.Option("Youtube", "--source", help="转载来源 (当 copyright=2 时使用)"),
    cover: str = typer.Option("", "--cover", help="本地封面文件路径 (留空则不设置封面)"),
):
    """One-click submit: auto-generate config and upload to BiliBili."""
    # Compute target workspace path
    target_root = workdir / video_id
    wp = ensure_workdir(target_root)

    console.print(f"视频 ID: {video_id}")
    console.print(f"工作目录: {target_root}")

    console.print(f"🚀 开始一键投稿流程: {workdir}")
    console.print()

    # Step 1: 检查必要文件
    console.print("📋 检查必要文件...")

    if not wp.video.exists():
        console.print(f"[red]❌ 找不到视频文件: {wp.video}[/red]")
        console.print("请先运行下载命令: youdoub yt dl <url>")
        console.print()
        console.print("[blue]💡 完整工作流程:[/blue]")
        console.print("   1. youdoub yt dl \"https://youtube.com/watch?v=VIDEO_ID\"")
        console.print("   2. youdoub yt translate-subs --lang zh-CN --backend deepseek --whole-file")
        console.print("   3. youdoub bili submit --title \"视频标题\"")
        raise typer.Exit(1)

    # 检查字幕文件（根据模式）
    subtitle_path = wp.out_zh() if subtitle_mode == "zh" else wp.out_bilingual
    subtitle_exists = subtitle_path.exists()

    console.print(f"[green]✅ 视频文件: {wp.video}[/green]")
    if subtitle_exists:
        console.print(f"[green]✅ 字幕文件: {subtitle_path} ({subtitle_mode})[/green]")
    else:
        console.print(f"[yellow]⚠️  找不到字幕文件: {subtitle_path}[/yellow]")
        console.print("将上传无字幕版本")

    # 检查是否有翻译后的字幕
    translated_sub = wp.translated_sub_srt()
    if not subtitle_exists and translated_sub.exists():
        console.print(f"[blue]💡 发现翻译字幕: {translated_sub}[/blue]")
        console.print("建议先生成最终字幕文件")

    # Step 2: 生成或检查配置
    console.print()
    console.print("⚙️  配置检查...")

    config_exists = wp.bili_config.exists()
    if not config_exists or force_config:
        console.print("📝 生成 biliup 配置...")
        try:
            config(
                video_id=video_id,
                workdir=workdir,
                title=title,
                desc=desc,
                tags=tags,
                tid=tid,
                subtitle_mode=subtitle_mode,
                copyright=copyright,
                source=source,
                cover=cover,
            )
        except Exception as e:
            console.print(f"[red]❌ 配置生成失败: {e}[/red]")
            raise typer.Exit(1)
    else:
        console.print(f"[green]✅ 使用现有配置: {wp.bili_config}[/green]")

    # Step 3: 执行上传
    console.print()
    console.print("📤 开始上传到 BiliBili...")

    try:
        upload(
            workdir=workdir,
            biliup_bin=biliup_bin,
        )
    except Exception as e:
        console.print(f"[red]❌ 上传失败: {e}[/red]")
        raise typer.Exit(1)

    # Step 4: 完成总结
    console.print()
    console.print("🎉 投稿流程完成！")
    console.print(f"📁 工作目录: {workdir}")
    console.print(f"📊 上传结果: {wp.bili_result}")

    # 显示结果摘要
    if wp.bili_result.exists():
        try:
            result = json.loads(wp.bili_result.read_text(encoding="utf-8"))
            returncode = result.get("returncode", -1)
            if returncode == 0:
                console.print("[green]✅ 上传成功！[/green]")
            else:
                console.print(f"[red]❌ 上传失败，返回码: {returncode}[/red]")
        except Exception:
            console.print("[yellow]⚠️  无法读取上传结果详情[/yellow]")


@app.command("workflow")
def workflow():
    """Show the complete YouDoub to BiliBili workflow."""
    console.print("[bold blue]🚀 YouDoub 完整工作流程[/bold blue]")
    console.print()

    console.print("[bold]第一阶段: 准备视频和字幕[/bold]")
    console.print("1. 下载 YouTube 视频:")
    console.print("   [cyan]youdoub yt dl \"https://youtube.com/watch?v=VIDEO_ID\"[/cyan]")
    console.print()

    console.print("2. 获取字幕 (可选):")
    console.print("   [cyan]youdoub yt sub --video-id VIDEO_ID[/cyan]")
    console.print()

    console.print("3. 翻译字幕:")
    console.print("   [cyan]youdoub yt translate-subs --video-id VIDEO_ID --lang zh-CN --backend deepseek --whole-file --merge-timelines --model deepseek-reasoner[/cyan]")
    console.print()

    console.print("[bold]第二阶段: 生成最终输出[/bold]")
    console.print("4. 生成双语字幕 (可选):")
    console.print("   [cyan]create_bilingual_subs.py[/cyan]")
    console.print()

    console.print("[bold]第三阶段: 投稿到 BiliBili[/bold]")
    console.print("5. 一键投稿 (推荐):")
    console.print("   [cyan]youdoub bili submit --video-id VIDEO_ID --title \"视频标题\" --desc \"视频描述\" --tags \"标签1,标签2\" --tid 123[/cyan]")
    console.print()

    console.print("   或者分步执行:")
    console.print("   a) 生成配置:")
    console.print("      [cyan]youdoub bili config --video-id VIDEO_ID --title \"视频标题\" --desc \"视频描述\"[/cyan]")
    console.print("   b) 执行上传:")
    console.print("      [cyan]youdoub bili upload --video-id VIDEO_ID[/cyan]")
    console.print()

    console.print("[bold green]💡 提示:[/bold green]")
    console.print("- 所有命令都在同一工作目录 (默认 ./work) 中运行")
    console.print("- 确保已安装 biliup 并配置好 BiliBili 账号")
    console.print("- 使用 --workdir 指定不同工作目录来处理多个视频")
    console.print("- 一键投稿 submit 命令会自动检查文件并生成配置")

