from __future__ import annotations

import json
import subprocess
from pathlib import Path

import typer
from rich.console import Console

from ..paths import ensure_workdir

app = typer.Typer(no_args_is_help=True)
console = Console()


@app.command("config")
def config(
    workdir: Path = typer.Option(Path("./work"), "--workdir", "-w", help="Workspace directory"),
    title: str = typer.Option("", "--title", help="BiliBili title (default from meta.json if available)"),
    desc: str = typer.Option("", "--desc", help="BiliBili description"),
    tags: str = typer.Option("", "--tags", help="Comma-separated tags"),
    tid: int = typer.Option(0, "--tid", help="BiliBili partition id (tid)"),
    subtitle_mode: str = typer.Option("zh", "--subtitle-mode", help="zh or bilingual"),
):
    """Generate biliup.yaml config in workdir/bili for later upload."""
    wp = ensure_workdir(workdir)

    # choose subtitle output
    subtitle_path = wp.out_zh() if subtitle_mode == "zh" else wp.out_bilingual

    # Try load title from meta
    meta_title = ""
    if wp.meta_json.exists():
        try:
            meta = json.loads(wp.meta_json.read_text(encoding="utf-8"))
            meta_title = meta.get("title") or ""
        except Exception:
            meta_title = ""

    title_final = title or meta_title or "Untitled"

    tag_list = [t.strip() for t in tags.split(",") if t.strip()]
    # Very small biliup config template.
    # NOTE: biliup config schema may differ by version; user can edit this file.
    yaml = "".join(
        [
            "# Auto-generated by youdoub\n",
            "\n",
            "common:\n",
            f"  title: {json.dumps(title_final, ensure_ascii=False)}\n",
            f"  desc: {json.dumps(desc, ensure_ascii=False)}\n" if desc else "  desc: \"\"\n",
            f"  tid: {tid}\n" if tid else "  tid: 0\n",
            f"  tags: {json.dumps(tag_list, ensure_ascii=False)}\n" if tag_list else "  tags: []\n",
            "\n",
            "videos:\n",
            "  - path: " + json.dumps(str(wp.video), ensure_ascii=False) + "\n",
        ]
    )

    # Subtitles: biliup support varies; we include a hint section.
    yaml += "\n# Subtitle hint (may require manual integration depending on biliup version)\n"
    yaml += "subtitle:\n"
    yaml += f"  path: {json.dumps(str(subtitle_path), ensure_ascii=False)}\n"

    wp.bili_config.write_text(yaml, encoding="utf-8")
    console.print(f"[green]OK[/green] wrote config: {wp.bili_config}")
    console.print("You may need to edit this yaml to match your biliup version/schema.")


@app.command("upload")
def upload(
    workdir: Path = typer.Option(Path("./work"), "--workdir", "-w", help="Workspace directory"),
    biliup_bin: str = typer.Option("biliup", "--biliup-bin", help="biliup executable"),
):
    """Upload to BiliBili via biliup using workdir/bili/biliup.yaml."""
    wp = ensure_workdir(workdir)

    if not wp.bili_config.exists():
        console.print(f"[red]Error: Missing biliup config {wp.bili_config}[/red]")
        console.print("Hint: run `youdoub bili config ...` first.")
        raise typer.Exit(1)

    # Call biliup. Exact command may vary by biliup version.
    cmd = [biliup_bin, "upload", "-c", str(wp.bili_config)]
    console.print("Running: " + " ".join(cmd))

    cp = subprocess.run(cmd)
    result = {
        "command": cmd,
        "returncode": cp.returncode,
    }
    wp.bili_result.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")

    if cp.returncode != 0:
        console.print(f"[red]Upload failed[/red], rc={cp.returncode}. See {wp.bili_result}")
        raise typer.Exit(cp.returncode)

    console.print(f"[green]OK[/green] upload finished. Result: {wp.bili_result}")

